# Generated by Django 2.1 on 2018-10-08 04:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSnomedConcepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('snomed_concept_code', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ReadCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_read_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SnomedConcept',
            fields=[
                ('external_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('file_path', models.CharField(max_length=255)),
                ('fsn_description', models.CharField(max_length=255)),
                ('external_fsn_description_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SnomedDescendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField()),
                ('descendant_external_id', models.ForeignKey(db_column='descendant_external_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept')),
            ],
        ),
        migrations.AddIndex(
            model_name='snomedconcept',
            index=models.Index(fields=['fsn_description'], name='snomedct_sn_fsn_des_84f149_idx'),
        ),
        migrations.AddIndex(
            model_name='snomedconcept',
            index=models.Index(fields=['external_id'], name='snomedct_sn_externa_21de76_idx'),
        ),
        migrations.AddField(
            model_name='readcode',
            name='concept_id',
            field=models.ForeignKey(db_column='concept_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept'),
        ),
        migrations.AddIndex(
            model_name='snomeddescendant',
            index=models.Index(fields=['external_id'], name='snomedct_sn_externa_18ef61_idx'),
        ),
        migrations.AddIndex(
            model_name='readcode',
            index=models.Index(fields=['concept_id'], name='snomedct_re_concept_458c16_idx'),
        ),
    ]
