# Generated by Django 2.1 on 2018-10-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0002_auto_20181016_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='snomedconcept',
            name='child',
            field=models.ManyToManyField(through='snomedct.SnomedDescendant', to='snomedct.SnomedConcept'),
        ),
        migrations.AlterField(
            model_name='snomeddescendant',
            name='descendant_external_id',
            field=models.ForeignKey(db_column='descendant_external_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendant_external_id', to='snomedct.SnomedConcept'),
        ),
        migrations.AlterField(
            model_name='snomeddescendant',
            name='external_id',
            field=models.ForeignKey(db_column='external_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='snomedct.SnomedConcept'),
        ),
    ]
