# Generated by Django 2.1 on 2018-09-28 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0002_commonsnomedconcepts'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='readcode',
            name='snomedct_re_concept_458c16_idx',
        ),
        migrations.RemoveField(
            model_name='commonsnomedconcepts',
            name='snomed_concept',
        ),
        migrations.RemoveField(
            model_name='readcode',
            name='concept_id',
        ),
        migrations.RemoveField(
            model_name='snomeddescendant',
            name='descendant_external_id',
        ),
    ]
