# Generated by Django 2.1 on 2018-09-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0003_auto_20180928_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snomedconcept',
            name='id',
        ),
        migrations.AlterField(
            model_name='snomedconcept',
            name='external_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
