# Generated by Django 2.1 on 2018-09-28 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0004_auto_20180928_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonsnomedconcepts',
            name='snomed_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept'),
        ),
        migrations.AddField(
            model_name='readcode',
            name='concept_id',
            field=models.ForeignKey(db_column='concept_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept'),
        ),
        migrations.AddField(
            model_name='snomeddescendant',
            name='descendant_external_id',
            field=models.ForeignKey(db_column='descendant_external_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept'),
        ),
        migrations.AddIndex(
            model_name='readcode',
            index=models.Index(fields=['concept_id'], name='snomedct_re_concept_458c16_idx'),
        ),
    ]
