# Generated by Django 2.1 on 2018-10-04 08:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0005_auto_20180928_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonsnomedconcepts',
            name='snomed_concept',
        ),
        migrations.AddField(
            model_name='commonsnomedconcepts',
            name='common_name',
            field=models.CharField(default='common', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commonsnomedconcepts',
            name='snomed_concept_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True), null=True, size=None),
        ),
    ]
