# Generated by Django 2.1 on 2018-09-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationfee',
            options={'verbose_name': 'Organisation Fee Structure', 'verbose_name_plural': 'Organisation Fee Structures'},
        ),
    ]
