# Generated by Django 2.1 on 2018-10-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationfee',
            options={'verbose_name': 'Organisation Fee Structure', 'verbose_name_plural': 'Organisation Fee Structures'},
        ),
        migrations.AlterField(
            model_name='organisationfee',
            name='gp_practice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationGeneralPractice', verbose_name='General Practice'),
        ),
    ]
