# Generated by Django 2.1 on 2018-10-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20181003_0958'),
        ('payment', '0002_auto_20180924_1822'),
    ]

    operations = [
    ]
