# Generated by Django 2.1 on 2018-10-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_merge_20181015_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationfee',
            name='amount_rate_lvl_4',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationfee',
            name='max_day_lvl_4',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
