# Generated by Django 2.1 on 2018-11-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20181022_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationfee',
            name='amount_rate_lvl_1',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for top payment band'),
        ),
        migrations.AlterField(
            model_name='organisationfee',
            name='amount_rate_lvl_2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for medium payment band'),
        ),
        migrations.AlterField(
            model_name='organisationfee',
            name='amount_rate_lvl_3',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for low payment band'),
        ),
        migrations.AlterField(
            model_name='organisationfee',
            name='amount_rate_lvl_4',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for lowest payment band'),
        ),
        migrations.AlterField(
            model_name='organisationfee',
            name='max_day_lvl_1',
            field=models.PositiveSmallIntegerField(verbose_name='Top payment band until day'),
        ),
        migrations.AlterField(
            model_name='organisationfee',
            name='max_day_lvl_2',
            field=models.PositiveSmallIntegerField(verbose_name='Medium payment band until day'),
        ),
        migrations.AlterField(
            model_name='organisationfee',
            name='max_day_lvl_3',
            field=models.PositiveSmallIntegerField(verbose_name='Low payment band until day'),
        ),
        migrations.AlterField(
            model_name='organisationfee',
            name='max_day_lvl_4',
            field=models.PositiveSmallIntegerField(verbose_name='Lowest payment band after day:'),
        ),
    ]
