# Generated by Django 2.1 on 2018-11-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20181106_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationfee',
            name='max_day_lvl_4',
            field=models.PositiveSmallIntegerField(verbose_name='Lowest payment band after day'),
        ),
    ]
