version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - master
          - develop
    docker:
      - image: circleci/python:3.6.5

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r config/requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: deploy UAT
          command: ./../.servers/.deploy-uat.sh
