version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - master
          - develop
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r config/requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    machine:
      enable: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0c:36:ab:0a:c6:dc:19:70:c4:40:32:b5:da:fc:7e:b2"
      - run:
          name: deploy UAT
          working_directory: ~/repo
          command: |
            ssh $UAT_USER@$UAT_HOST "$UAT_COMMAND"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
