version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: medi-{{ .Branch }}-{{ checksum "config/requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r config/requirements.txt
      - save_cache:
          key: medi-{{ .Branch }}-{{ checksum "config/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy_staging:
    machine:
      enable: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "df:14:25:0d:9a:e8:85:25:da:0e:8a:99:33:f9:24:d6"
      - run:
          name: Deploy staging
          working_directory: ~/repo
          command: |
            ssh $STAGING_USER@$STAGING_HOST "$STAGING_COMMAND"
  deploy_uat:
    machine:
      enable: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0c:36:ab:0a:c6:dc:19:70:c4:40:32:b5:da:fc:7e:b2"
      - run:
          name: Deploy UAT
          working_directory: ~/repo
          command: |
            ssh $UAT_USER@$UAT_HOST "$UAT_COMMAND"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - deploy_uat:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
