# Generated by Django 2.1 on 2018-08-14 05:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationclient',
            old_name='role',
            new_name='type',
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='division',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='can_create_amra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='can_create_sars',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='companies_house_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='contact_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='fca_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='generic_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='generic_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='vat_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
