# Generated by Django 2.1 on 2018-10-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreportauth',
            name='token',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
