# Generated by Django 2.1 on 2018-11-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20181031_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreportauth',
            name='token',
        ),
        migrations.AddField(
            model_name='patientreportauth',
            name='mobi_request_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientreportauth',
            name='verify_pin',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
