# Generated by Django 2.1 on 2018-11-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20181107_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreportauth',
            name='verify_pin',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
