# Generated by Django 2.1 on 2019-03-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0032_auto_20190301_0951'),
        ('report', '0008_remove_patientreportauth_report_de_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionMerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file_detail', models.TextField(blank=True, null=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.Instruction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
