# Generated by Django 2.1 on 2018-10-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('role', models.IntegerField(choices=[('', '----'), (0, 'Manager'), (1, 'GP'), (2, 'SARS')], verbose_name='Role')),
                ('create_amra', models.BooleanField(default=False, verbose_name='Create AMRA')),
                ('create_sars', models.BooleanField(default=False, verbose_name='Create SARS')),
                ('reject_amra', models.BooleanField(default=False, verbose_name='Reject AMRA')),
                ('reject_sars', models.BooleanField(default=False, verbose_name='Reject SARS')),
                ('process_amra', models.BooleanField(default=False, verbose_name='Process AMRA')),
                ('process_sars', models.BooleanField(default=False, verbose_name='Process SARS')),
                ('allocate_gp', models.BooleanField(default=False, verbose_name='Allocate to GP')),
                ('sign_off_amra', models.BooleanField(default=False, verbose_name='Sign off AMRA')),
                ('sign_off_sars', models.BooleanField(default=False, verbose_name='Sign off SARS')),
                ('view_completed_amra', models.BooleanField(default=False, verbose_name='View completed AMRA')),
                ('view_completed_sars', models.BooleanField(default=False, verbose_name='View completed SARS')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='instructionpermission',
            unique_together={('role',)},
        ),
    ]
