# Generated by Django 2.1 on 2018-11-09 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[('', '----'), (0, 'Manager'), (1, 'GP'), (2, 'Other practice staff')], verbose_name='Role')),
                ('create_sars', models.BooleanField(default=False, verbose_name='Create SARS')),
                ('reject_amra', models.BooleanField(default=False, verbose_name='Reject AMRA')),
                ('reject_sars', models.BooleanField(default=False, verbose_name='Reject SARS')),
                ('process_amra', models.BooleanField(default=False, verbose_name='Process AMRA')),
                ('process_sars', models.BooleanField(default=False, verbose_name='Process SARS')),
                ('allocate_gp', models.BooleanField(default=False, verbose_name='Allocate to other user to process')),
                ('sign_off_amra', models.BooleanField(default=False, verbose_name='Sign off AMRA')),
                ('sign_off_sars', models.BooleanField(default=False, verbose_name='Sign off SARS')),
                ('view_completed_amra', models.BooleanField(default=False, verbose_name='View completed AMRA')),
                ('view_completed_sars', models.BooleanField(default=False, verbose_name='View completed SARS')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationGeneralPractice')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='instructionpermission',
            unique_together={('role', 'organisation')},
        ),
    ]
