# Generated by Django 2.1 on 2018-11-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionpermission',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='instructionpermission',
            name='role',
            field=models.IntegerField(choices=[('', '----'), (0, 'Manager'), (1, 'GP'), (2, 'Other practice staff')], null=True, verbose_name='Role'),
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='allocate_gp',
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='create_sars',
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='process_amra',
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='process_sars',
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='reject_amra',
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='reject_sars',
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='sign_off_amra',
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='sign_off_sars',
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='view_completed_amra',
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='view_completed_sars',
        ),
        migrations.AlterUniqueTogether(
            name='instructionpermission',
            unique_together={('role', 'organisation', 'group')},
        ),
    ]
