# Generated by Django 2.1 on 2018-10-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionpermission',
            name='role',
            field=models.IntegerField(choices=[('', '----'), (0, 'Manager'), (1, 'GP'), (2, 'Other practice staff')], verbose_name='Role'),
        ),
    ]
