# Generated by Django 2.1 on 2018-11-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20181030_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionpermission',
            name='create_amra',
        ),
        migrations.AlterField(
            model_name='instructionpermission',
            name='allocate_gp',
            field=models.BooleanField(default=False, verbose_name='Allocate to other user to process'),
        ),
    ]
