# Generated by Django 2.1 on 2018-11-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20181113_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
