# Generated by Django 2.1 on 2018-11-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_merge_20181102_0749'),
        ('permissions', '0003_auto_20181101_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionpermission',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationGeneralPractice'),
        ),
        migrations.AlterUniqueTogether(
            name='instructionpermission',
            unique_together={('role', 'organisation')},
        ),
    ]
