# Generated by Django 2.1 on 2018-11-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_auto_20181102_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionpermission',
            name='created',
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='instructionpermission',
            name='modified',
        ),
    ]
