# Generated by Django 2.1 on 2018-08-22 05:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20180822_0619'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('userprofilebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.UserProfileBase')),
                ('nhs_number', models.CharField(blank=True, max_length=10)),
                ('emis_number', models.CharField(max_length=255)),
                ('vision_number', models.CharField(max_length=255)),
                ('systmone_number', models.CharField(max_length=255)),
                ('microtest_number', models.CharField(max_length=255)),
                ('organization_gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationGeneralPractice')),
            ],
            options={
                'verbose_name': 'Patient User',
            },
            bases=('accounts.userprofilebase',),
        ),
        migrations.AddField(
            model_name='userprofilebase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofilebase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofilebase',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
