# Generated by Django 2.1 on 2018-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpracticeuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[('', '----'), (0, 'Manager'), (1, 'GP'), (2, 'SARS')], null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userprofilebase',
            name='title',
            field=models.CharField(blank=True, choices=[('', '----'), ('DR', 'Dr.'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('MX', 'Mx.')], max_length=3),
        ),
    ]
