# Generated by Django 2.1 on 2018-10-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181022_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpracticeuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[('', '----'), (0, 'Manager'), (1, 'GP'), (2, 'Other practice staff')], null=True, verbose_name='Role'),
        ),
    ]
