# Generated by Django 2.1 on 2018-08-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180822_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilebase',
            name='telephone_home',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofilebase',
            name='telephone_mobile',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
