# Generated by Django 2.1 on 2018-08-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180823_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='organization_gp',
            new_name='organisation_gp',
        ),
    ]
