# Generated by Django 2.1 on 2018-10-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181029_1247'),
        ('accounts', '0003_auto_20181030_0457'),
    ]

    operations = [
    ]
