# Generated by Django 2.1 on 2018-08-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180828_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('MEDI', 'Medidata'), ('CLT', 'Client'), ('GP', 'General Practice'), ('PAT', 'Patient')], max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofilebase',
            name='title',
            field=models.CharField(blank=True, choices=[('DR', 'Dr.'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('MX', 'Mx.')], max_length=3),
        ),
    ]
