# Generated by Django 2.1 on 2018-10-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20181030_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilebase',
            name='address_name_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofilebase',
            name='title',
            field=models.CharField(choices=[('', '----'), ('DR', 'Dr.'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('MX', 'Mx.')], max_length=3),
        ),
    ]
