# Generated by Django 2.1 on 2018-10-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181031_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpPractices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('comm_area', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('billing_address_street1', models.CharField(max_length=255)),
                ('billing_address_street2', models.CharField(max_length=255, null=True)),
                ('billing_address_street3', models.CharField(max_length=255, null=True)),
                ('billing_address_street', models.CharField(max_length=255)),
                ('billing_address_city', models.CharField(max_length=255)),
                ('billing_address_state', models.CharField(max_length=255)),
                ('billing_address_postalcode', models.CharField(max_length=255)),
                ('phone_office', models.CharField(max_length=255)),
                ('phone_alternate', models.CharField(max_length=255, null=True)),
                ('respcode_c', models.CharField(max_length=255)),
                ('salutatuin', models.CharField(max_length=255)),
                ('initials', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('patientlistsize_c', models.CharField(max_length=255)),
                ('urn_c', models.CharField(max_length=255)),
                ('sitenumber_c', models.CharField(max_length=255)),
                ('employees', models.CharField(max_length=255)),
                ('ownership', models.CharField(max_length=255)),
                ('ccg_health_board_c', models.CharField(max_length=255)),
                ('sic_code', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('greeting', models.CharField(max_length=255)),
                ('email1', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
