# Generated by Django 2.1 on 2018-10-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_gppractices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gppractices',
            old_name='salutatuin',
            new_name='salutation',
        ),
    ]
