# Generated by Django 2.1 on 2018-10-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180928_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Client Admin'), (1, 'Client')], null=True, verbose_name='Role'),
        ),
    ]
