# Generated by Django 2.1 on 2018-10-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181024_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='gppractices',
            name='practicemanagername_c',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
