# Generated by Django 2.1 on 2018-10-24 14:01

from django.db import migrations
import os
from django.conf import settings

def parser():
    path = os.path.join(os.path.dirname(settings.BASE_DIR), 'initial_data/mohara_csv_dump.sql')
    insert_data = str()
    with open(path) as file:
        for line in file:
            insert_data = insert_data + line

        return insert_data



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_gppractices_practicemanagername_c'),
    ]

    operations = [
        migrations.RunSQL(parser())
    ]
