# Generated by Django 2.1 on 2018-10-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0005_auto_20180928_0456'),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateConditionsOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snomedct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept')),
                ('template_instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.TemplateInstruction')),
            ],
            options={
                'verbose_name': 'Template Conditions Of Interest',
            },
        ),
    ]
