# Generated by Django 2.1 on 2018-10-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_templateconditionsofinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateinstruction',
            name='client_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationClient'),
        ),
    ]
