# Generated by Django 2.1 on 2018-10-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_auto_20181003_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateinstruction',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
