# Generated by Django 2.1 on 2018-10-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_auto_20181017_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateinstruction',
            old_name='title',
            new_name='template_title',
        ),
    ]
