# Generated by Django 2.1 on 2018-09-11 08:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructions', '0001_initial'),
        ('snomedct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=255)),
                ('reaction', models.CharField(max_length=255)),
                ('date_discovered', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalMedicationRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescribed_from', models.DateField()),
                ('prescribed_to', models.DateField()),
                ('notes', models.TextField()),
                ('repeat', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Redaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_notes', models.TextField()),
                ('acute_prescription_notes', models.TextField()),
                ('repeat_prescription_notes', models.TextField()),
                ('referral_notes', models.TextField()),
                ('significant_problem_notes', models.TextField()),
                ('attachment_notes', models.TextField()),
                ('bloods_notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redacted_xpaths', django.contrib.postgres.fields.jsonb.JSONField()),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.Instruction')),
            ],
        ),
        migrations.AddField(
            model_name='additionalmedicationrecords',
            name='redaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalreport.Redaction'),
        ),
        migrations.AddField(
            model_name='additionalmedicationrecords',
            name='snomed_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept'),
        ),
        migrations.AddField(
            model_name='additionalallergy',
            name='redaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalreport.Redaction'),
        ),
    ]
