# Generated by Django 2.1 on 2018-10-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendmentsforrecord',
            name='instruction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructions.Instruction'),
        ),
    ]
