# Generated by Django 2.1 on 2018-09-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0002_auto_20180913_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='redaction',
            name='patient_emis_number',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
