# Generated by Django 2.1 on 2018-10-02 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicalreport', '0004_auto_20180917_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='redaction',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='redaction',
            name='review_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('DRAFT', 'Draft'), ('SUBMIT', 'Submit')], default='NEW', max_length=6),
        ),
    ]
