# Generated by Django 2.1 on 2019-01-18 07:09

from django.db import migrations, models
import django.db.models.deletion


def clean_prepared_by_fields(apps, schema_editor):
    AmendmentsForRecord = apps.get_model('medicalreport', 'AmendmentsForRecord')
    GeneralPracticeUser = apps.get_model('accounts', 'GeneralPracticeUser')
    for record in AmendmentsForRecord.objects.all():
        record.prepared_by = GeneralPracticeUser.objects.first()
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0004_referencephrases'),
    ]

    operations = [
        migrations.RunPython(clean_prepared_by_fields),
        migrations.AlterField(
            model_name='amendmentsforrecord',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.GeneralPracticeUser'),
        ),
        migrations.AlterField(
            model_name='amendmentsforrecord',
            name='submit_choice',
            field=models.CharField(blank=True, choices=[('PREPARED_AND_SIGNED', 'Prepared and signed directly by {}'), ('PREPARED_AND_REVIEWED', 'Signed off by <span id="preparer"></span>')], max_length=255),
        ),
    ]
