# Generated by Django 2.1 on 2018-10-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0004_auto_20181022_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amendmentsforrecord',
            name='patient_emis_number',
        ),
    ]
