# Generated by Django 2.1 on 2018-10-04 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0005_auto_20181002_0506'),
    ]

    operations = [
    ]
