# Generated by Django 2.1 on 2018-10-03 08:43

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructions', '0008_instruction_rejected_reason'),
        ('medicalreport', '0005_auto_20181002_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmendmentsForRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_notes', models.TextField(null=True)),
                ('acute_prescription_notes', models.TextField(null=True)),
                ('repeat_prescription_notes', models.TextField(null=True)),
                ('referral_notes', models.TextField(null=True)),
                ('significant_problem_notes', models.TextField(null=True)),
                ('attachment_notes', models.TextField(null=True)),
                ('bloods_notes', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_emis_number', models.CharField(default=None, max_length=255, null=True)),
                ('redacted_xpaths', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('submit_choice', models.CharField(blank=True, choices=[('PREPARED_AND_SIGNED', 'Prepared and signed directly by'), ('PREPARED_AND_REVIEWED', 'Prepared by <span id="preparer"></span>  and reviewed by')], max_length=255)),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('DRAFT', 'Draft'), ('SUBMIT', 'Submit')], default='NEW', max_length=6)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.Instruction')),
                ('review_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='redaction',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='redaction',
            name='review_by',
        ),
        migrations.AlterField(
            model_name='additionalallergies',
            name='redaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalreport.AmendmentsForRecord'),
        ),
        migrations.AlterField(
            model_name='additionalmedicationrecords',
            name='redaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalreport.AmendmentsForRecord'),
        ),
        migrations.DeleteModel(
            name='Redaction',
        ),
    ]
