# Generated by Django 2.1 on 2018-11-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0006_nhssensitiveconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhssensitiveconditions',
            name='group',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='nhssensitiveconditions',
            name='snome_code',
            field=models.CharField(max_length=128),
        ),
    ]
