# Generated by Django 2.1 on 2018-10-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0007_auto_20181004_0914'),
    ]

    operations = [
        migrations.RenameModel('Redaction', 'AmendmentsForRecord')
    ]
