# Generated by Django 2.1 on 2018-10-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0008_auto_20181004_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalallergies',
            name='redaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalreport.AmendmentsForRecord'),
        ),
        migrations.AlterField(
            model_name='additionalmedicationrecords',
            name='redaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalreport.AmendmentsForRecord'),
        ),
    ]
