# Generated by Django 2.1 on 2018-10-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0009_auto_20181004_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalallergies',
            old_name='redaction',
            new_name='amendments_for_record',
        ),
        migrations.RenameField(
            model_name='additionalmedicationrecords',
            old_name='redaction',
            new_name='amendments_for_record',
        ),
    ]
