# Generated by Django 2.1 on 2018-10-04 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0010_auto_20181004_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendmentsforrecord',
            name='submit_choice',
            field=models.CharField(blank=True, choices=[('PREPARED_AND_SIGNED', 'Prepared and signed directly by'), ('PREPARED_AND_REVIEWED', 'Prepared by <span id="preparer"></span>  and reviewed by')], max_length=255),
        ),
        migrations.AlterField(
            model_name='amendmentsforrecord',
            name='review_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
