# Generated by Django 2.1 on 2018-08-22 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180822_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('completed_signed_off_timestamp', models.DateTimeField(blank=True, null=True)),
                ('rejected_timestamp', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('AMRA', 'AMRA'), ('SARS', 'SARS')], max_length=4)),
                ('final_report_date', models.TextField(blank=True)),
                ('initial_monetary_value', models.FloatField(blank=True, null=True, verbose_name='Value £')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Overdue'), (3, 'Complete'), (4, 'Reject')])),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ClientUser', verbose_name='Client')),
                ('gp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.GeneralPracticeUser', verbose_name='GP Allocated')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Instruction',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='InstructionAdditionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('response_mandatory', models.BooleanField(default=False)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.Instruction')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionConditionsOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readcode2_code', models.CharField(blank=True, max_length=255)),
                ('SNOMEDCT_code', models.CharField(max_length=255)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.Instruction')),
            ],
        ),
    ]
