# Generated by Django 2.1 on 2018-08-31 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ('-created',), 'verbose_name': 'Instruction'},
        ),
        migrations.AlterModelOptions(
            name='instructionadditionquestion',
            options={'verbose_name': 'Instruction Addition Question'},
        ),
        migrations.AlterModelOptions(
            name='instructionconditionsofinterest',
            options={'verbose_name': 'Instruction Conditions Of Interest'},
        ),
        migrations.AddField(
            model_name='instruction',
            name='consent_form',
            field=models.FileField(null=True, upload_to='consent_forms'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='gp_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.GeneralPracticeUser', verbose_name='GP Allocated'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Overdue'), (3, 'Complete'), (4, 'Reject')], default=0),
        ),
    ]
