# Generated by Django 2.1 on 2018-11-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_auto_20181113_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='date_range_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='date_range_to',
            field=models.DateField(null=True),
        ),
    ]
