# Generated by Django 2.1 on 2018-09-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_auto_20180831_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionadditionquestion',
            name='question',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
