# Generated by Django 2.1 on 2018-09-12 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('instructions', '0002_auto_20180831_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='gp_practice_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='gp_practice_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
