# Generated by Django 2.1 on 2018-10-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_auto_20181009_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='gp_initial_from_client',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='instruction',
            name='gp_last_name_from_client',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='instruction',
            name='gp_title_from_client',
            field=models.CharField(blank=True, choices=[('DR', 'Dr.'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('MX', 'Mx.')], max_length=5),
        ),
    ]
