# Generated by Django 2.1 on 2018-10-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0003_auto_20181011_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_form', models.FileField(blank=True, null=True, upload_to='consent_forms')),
                ('site', models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
