# Generated by Django 2.1 on 2018-09-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0002_commonsnomedconcepts'),
        ('instructions', '0003_auto_20180913_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionconditionsofinterest',
            name='SNOMEDCT_code',
        ),
        migrations.RemoveField(
            model_name='instructionconditionsofinterest',
            name='readcode2_code',
        ),
        migrations.AddField(
            model_name='instructionconditionsofinterest',
            name='snomedct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept'),
        ),
    ]
