# Generated by Django 2.1 on 2018-11-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0003_auto_20181116_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='policy_form',
        ),
    ]
