# Generated by Django 2.1 on 2018-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0004_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='gp_title_from_client',
            field=models.CharField(blank=True, choices=[('', '----'), ('DR', 'Dr.'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('MX', 'Mx.')], max_length=5),
        ),
    ]
