# Generated by Django 2.1 on 2018-10-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0004_auto_20180918_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='consent_form',
            field=models.FileField(blank=True, null=True, upload_to='consent_forms'),
        ),
    ]
