# Generated by Django 2.1 on 2018-10-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0005_auto_20181022_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='policy_form',
            field=models.FileField(blank=True, null=True, upload_to='policy_forms'),
        ),
    ]
