# Generated by Django 2.1 on 2018-10-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0006_setting_policy_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionAdditionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Instruction Addition Answer',
            },
        ),
        migrations.AlterField(
            model_name='instructionadditionquestion',
            name='instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addition_questions', to='instructions.Instruction'),
        ),
        migrations.AddField(
            model_name='instructionadditionanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructions.InstructionAdditionQuestion'),
        ),
    ]
