# Generated by Django 2.1 on 2018-10-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0006_instruction_rejected_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='rejected_reason',
            new_name='rejected_note',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='rejected_type',
        ),
    ]
