# Generated by Django 2.1 on 2018-10-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0007_auto_20181025_1049'),
        ('instructions', '0007_instruction_rejected_by'),
    ]

    operations = [
    ]
