# Generated by Django 2.1 on 2018-11-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0008_merge_20181025_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Overdue'), (3, 'Completed'), (4, 'Rejected')], default=0),
        ),
    ]
