# Generated by Django 2.1 on 2018-11-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0009_auto_20181105_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='mdx_consent',
            field=models.FileField(blank=True, null=True, upload_to='consent_forms'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='sars_consent',
            field=models.FileField(blank=True, null=True, upload_to='consent_forms'),
        ),
    ]
