# Generated by Django 2.1 on 2019-03-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0039_auto_20190314_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='ins_amount_rate_lvl_1',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='ins_amount_rate_lvl_2',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='ins_amount_rate_lvl_3',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='ins_amount_rate_lvl_4',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='ins_max_day_lvl_1',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='instruction',
            name='ins_max_day_lvl_2',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='instruction',
            name='ins_max_day_lvl_3',
            field=models.PositiveSmallIntegerField(default=11),
        ),
        migrations.AddField(
            model_name='instruction',
            name='ins_max_day_lvl_4',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
