# Generated by Django 2.1 on 2019-03-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0039_auto_20190319_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='type_catagory',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
