# Generated by Django 2.1 on 2019-03-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0040_auto_20190319_0801'),
        ('instructions', '0039_auto_20190319_0318'),
    ]

    operations = [
    ]
