# Generated by Django 2.1 on 2019-03-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0041_merge_20190320_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='ins_amount_rate_lvl_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='ins_amount_rate_lvl_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='ins_amount_rate_lvl_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='ins_amount_rate_lvl_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
