# Generated by Django 2.1 on 2019-03-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0043_auto_20190322_0548'),
        ('instructions', '0040_instruction_type_catagory'),
    ]

    operations = [
    ]
