# Generated by Django 2.1 on 2019-03-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0044_merge_20190322_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='type_catagory',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
