# Generated by Django 2.1 on 2018-11-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NHSGeneralPractice',
        ),
    ]
