# Generated by Django 2.1 on 2018-10-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationgeneralpractice',
            name='operating_system_auth_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisationgeneralpractice',
            name='operating_system_socket_endpoint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisationgeneralpractice',
            name='payment_preference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisationgeneralpractice',
            name='payment_timing',
            field=models.CharField(blank=True, choices=[('AR', 'Arrears'), ('AD', 'Advance')], max_length=2),
        ),
    ]
