# Generated by Django 2.1 on 2018-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20181022_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationgeneralpractice',
            name='accept_policy',
            field=models.BooleanField(default=True),
        ),
    ]
