# Generated by Django 2.1 on 2018-11-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_delete_nhsgeneralpractice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationbase',
            options={'permissions': (('view_user_management', 'Can view User Management'), ('add_user_management', 'Can add User Management'), ('change_user_management', 'Can change User Management'), ('delete_user_management', 'Can delete User Management')), 'verbose_name': 'Organisation'},
        ),
    ]
