# Generated by Django 2.1 on 2018-11-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisationgeneralpractice_accept_policy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NHSgpPractice',
            new_name='NHSGeneralPractice',
        ),
    ]
