# Generated by Django 2.1 on 2018-09-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20180823_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationgeneralpractice',
            name='payment_preference',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
