# Generated by Django 2.1 on 2018-11-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20181101_0948'),
        ('organisations', '0004_auto_20181102_0549'),
    ]

    operations = [
    ]
