# Generated by Django 2.1 on 2018-10-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emrsetup',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emrsetup',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emrsetup',
            name='receive_email',
            field=models.EmailField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
