MANAGER_PERMISSIONS=[
    'view_user_management',
    'change_user_management',
    'delete_user_management',
    'add_user_management',
    'view_instruction',
    'view_organisationfee',
    'view_instructionpermission',
    'add_instructionpermission',
    'change_instructionpermission',
    'delete_instructionpermission'
]

GP_PERMISSIONS=[
    'view_instruction',
]

OTHER_PERMISSIONS=[
    'view_instruction',
]

CLIENT_PERMISSIONS=[
    'view_instruction',
    'add_instruction',
    'delete_instruction',
    'change_instruction'
]

ADMIN_PERMISSIONS=[
    'view_user_management',
    'change_user_management',
    'delete_user_management',
    'add_user_management',
    'view_instruction',
    'add_instruction',
    'delete_instruction',
    'change_instruction',
    'view_organisationfee',
    'view_templateinstruction',
    'view_summry_report'
]

MEDI_PERMISSIONS=[
    'view_user_management',
    'change_user_management',
    'delete_user_management',
    'add_user_management',
    'view_instruction',
    'view_organisationfee',
    'view_instructionpermission',
    'add_instructionpermission',
    'change_instructionpermission',
    'change_user',
    'delete_instructionpermission'
]

MEDI_ADMIN_PERMISSIONS=[
    'view_patient',
    'view_user',
    'change_user',
    'add_user',
    'delete_user',
    'view_userprofilebase',
    'change_userprofilebase',
    'add_userprofilebase',
    'delete_userprofilebase',
    'view_generalpracticeuser',
    'change_generalpracticeuser',
    'delete_generalpracticeuser',
    'add_generalpracticeuser',
    'add_medidatauser',
    'change_medidatauser',
    'delete_medidatauser',
    'view_medidatauser',
    'view_group',
    'add_clientnote',
    'change_clientnote',
    'delete_clientnote',
    'view_clientnote',
    'view_instruction',
    'add_instructionclientnote',
    'change_instructionclientnote',
    'delete_instructionclientnote',
    'view_instructionclientnote',
    'add_instructionadditionquestion',
    'change_instructionadditionquestion',
    'delete_instructionadditionquestion',
    'view_instructionadditionquestion',
    'view_instructionpatient',
    'view_organisationclient',
    'add_organisationclient',
    'change_organisationclient',
    'delete_organisationclient',
    'view_organisationgeneralpractice',
    'change_organisationgeneralpractice',
    'view_organisationmedidata',
    'add_instructionvolumefee',
    'change_instructionvolumefee',
    'delete_instructionvolumefee',
    'view_instructionvolumefee',
    'view_organisationfee',
    'view_instructionpermission',
    'view_thirdpartyauthorisation',
    'view_patientreportauth',
    'add_templateinstruction',
    'change_templateinstruction',
    'delete_templateinstruction',
    'view_templateinstruction',
    'add_templateadditionalquestion',
    'change_templateadditionalquestion',
    'delete_templateadditionalquestion',
    'view_templateadditionalquestion',
    'add_templateadditionalcondition',
    'change_templateadditionalcondition',
    'delete_templateadditionalcondition',
    'view_templateadditionalcondition'
]

MEDI_TEAM_PERMISSIONS=[
    'view_patient',
    'view_user',
    'change_user',
    'view_userprofilebase',
    'change_userprofilebase',
    'view_generalpracticeuser',
    'change_generalpracticeuser',
    'view_medidatauser',
    'change_medidatauser',
    'view_instruction',
    'change_instruction',
    'add_clientnote',
    'change_clientnote',
    'delete_clientnote',
    'view_clientnote',
    'add_instructionclientnote',
    'change_instructionclientnote',
    'delete_instructionclientnote',
    'view_instructionclientnote',
    'view_instructionpatient',
    'view_organisationclient',
    'view_organisationgeneralpractice',
    'change_organisationgeneralpractice',
    'view_organisationfee',
    'view_thirdpartyauthorisation',
    'view_patientreportauth'
]

INSTRUCTION_PERMISSIONS=[
    'create_sars',
    'reject_amra',
    'reject_sars',
    'process_amra',
    'process_sars',
    'allocate_gp',
    'sign_off_amra',
    'sign_off_sars',
    'view_completed_amra',
    'view_completed_sars',
    'view_summry_report',
]
