AMRA_TYPE = 'AMRA'
SARS_TYPE = 'SARS'

INSTRUCTION_TYPE_CHOICES = (
    (AMRA_TYPE, 'AMRA'),
    (SARS_TYPE, 'SARS')
)


INSTRUCTION_STATUS_NEW = 0
INSTRUCTION_STATUS_PROGRESS = 1
INSTRUCTION_STATUS_OVERDUE = 2
INSTRUCTION_STATUS_COMPLETE = 3
INSTRUCTION_STATUS_REJECT = 4

INSTRUCTION_STATUS_CHOICES = (
    (INSTRUCTION_STATUS_NEW, 'New'),
    (INSTRUCTION_STATUS_PROGRESS, 'In Progress'),
    (INSTRUCTION_STATUS_OVERDUE, 'Overdue'),
    (INSTRUCTION_STATUS_COMPLETE, 'Complete'),
    (INSTRUCTION_STATUS_REJECT, 'Reject')
)